# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180411_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_from',
            field=models.IntegerField(choices=[(0, '原创'), (1, '转载')], default=0, verbose_name='文章来源'),
        ),
    ]
