# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/1.jpg', upload_to='images/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', 1), ('女', 0)], default=1, max_length=1, verbose_name='性别'),
        ),
    ]
