# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180409_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default='This guy is too lazy to leave anything here!', max_length=128),
        ),
    ]
