# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 10:02
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, default='评论', verbose_name='评论内容'),
        ),
    ]
